
DROP TABLE IF EXISTS RECORDING, TAGGED_TRACK, TAGGED_ALBUM, BELONGS_TO, OWNED_BY, CONTAINS, ALBUM_TRACK, PLAYLIST, TRACK, ALBUM, GROUP_TABLE, ARTIST, RECORD_LABEL, SUBSCRIPTION, USER_TABLE, RIGHTS_HOLDER, STUDIO, GENRE;


CREATE TABLE GENRE (
    ID_GENRE INT PRIMARY KEY,
    G_NAME VARCHAR(100) NOT NULL UNIQUE,
    G_DESCRIPTION VARCHAR(255),
    G_ORIGIN VARCHAR(100),
    G_POPULARITY INT NOT NULL
);

CREATE TABLE SUBSCRIPTION (
    ID_SUBSCRIPTION INT PRIMARY KEY,
    S_TYPE VARCHAR(20) NOT NULL,
    S_START_DATE DATE NOT NULL,
    S_END_DATE DATE,
    S_STATUS VARCHAR(20) NOT NULL
);

CREATE TABLE RECORD_LABEL (
    ID_LABEL INT PRIMARY KEY,
    RL_NAME VARCHAR(255) NOT NULL,
    RL_COUNTRY VARCHAR(100) NOT NULL,
    RL_CREATION_DATE DATE,
    RL_WEBSITE VARCHAR(255)
);

CREATE TABLE STUDIO (
    ID_STUDIO INT PRIMARY KEY,
    ST_NAME VARCHAR(255) NOT NULL,
    ST_CITY VARCHAR(100) NOT NULL,
    ST_COUNTRY VARCHAR(100) NOT NULL,
    ST_CAPACITY INT
);

CREATE TABLE TRACK (
    ID_TRACK INT PRIMARY KEY,
    T_TITLE VARCHAR(255) NOT NULL,
    T_DURATION INT NOT NULL,
    T_ISRC VARCHAR(15) UNIQUE NOT NULL,
    T_EXPLICIT BOOLEAN NOT NULL
);

CREATE TABLE USER (
    ID_USER INT PRIMARY KEY,
    U_EMAIL VARCHAR(255) UNIQUE NOT NULL,
    U_PASSWORD VARCHAR(255) NOT NULL,
    U_REGISTRATION_DATE DATE NOT NULL,
    U_COUNTRY VARCHAR(100) NOT NULL,
    ID_SUBSCRIPTION INT NOT NULL,
    FOREIGN KEY (ID_SUBSCRIPTION) REFERENCES SUBSCRIPTION(ID_SUBSCRIPTION) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ARTIST (
    ID_ARTIST INT PRIMARY KEY,
    A_NAME VARCHAR(255) NOT NULL,
    A_CAREER_START DATE,
    A_ORIGIN_COUNTRY VARCHAR(100) NOT NULL,
    ID_MENTOR INT, 
    FOREIGN KEY (ID_MENTOR) REFERENCES ARTIST(ID_ARTIST) ON DELETE SET NULL
);

CREATE TABLE ALBUM (
    ID_ALBUM INT PRIMARY KEY,
    A_TITLE VARCHAR(255) NOT NULL,
    A_RELEASE_DATE DATE NOT NULL,
    A_POPULARITY INT NOT NULL,
    ID_LABEL INT,
    ID_ARTIST INT NOT NULL,
    FOREIGN KEY (ID_LABEL) REFERENCES RECORD_LABEL(ID_LABEL) ON DELETE SET NULL,
    FOREIGN KEY (ID_ARTIST) REFERENCES ARTIST(ID_ARTIST) ON DELETE CASCADE
);


CREATE TABLE ALBUM_TRACK (
    ID_ALBUM INT,
    TRACK_NUMBER INT,
    AT_DURATION INT NOT NULL,
    AT_DISPLAYED_TITLE VARCHAR(255) NOT NULL,
    ID_TRACK INT NOT NULL,
    PRIMARY KEY (ID_ALBUM, TRACK_NUMBER),
    FOREIGN KEY (ID_ALBUM) REFERENCES ALBUM(ID_ALBUM) ON DELETE CASCADE,
    FOREIGN KEY (ID_TRACK) REFERENCES TRACK(ID_TRACK) ON DELETE CASCADE
);


CREATE TABLE RECORDING (
    ID_RECORDING INT PRIMARY KEY,
    ID_TRACK INT NOT NULL,
    ID_ARTIST INT NOT NULL,
    ID_STUDIO INT NOT NULL,
    recording_date DATE NOT NULL,
    FOREIGN KEY (ID_TRACK) REFERENCES TRACK(ID_TRACK) ON DELETE CASCADE,
    FOREIGN KEY (ID_ARTIST) REFERENCES ARTIST(ID_ARTIST) ON DELETE CASCADE,
    FOREIGN KEY (ID_STUDIO) REFERENCES STUDIO(ID_STUDIO) ON DELETE CASCADE
);

CREATE TABLE PLAYLIST (
    ID_PLAYLIST INT PRIMARY KEY,
    P_NAME VARCHAR(255) NOT NULL,
    P_CREATION_DATE DATE NOT NULL,
    P_PUBLIC BOOLEAN NOT NULL,
    ID_USER INT NOT NULL,
    FOREIGN KEY (ID_USER) REFERENCES USER(ID_USER) ON DELETE CASCADE
);