ALTER TABLE ALBUM ADD CONSTRAINT chk_a_popularity CHECK (A_POPULARITY BETWEEN 0 AND 100);

ALTER TABLE GENRE ADD CONSTRAINT chk_g_popularity CHECK (G_POPULARITY BETWEEN 0 AND 100);

ALTER TABLE USER ADD CONSTRAINT chk_u_email CHECK (U_EMAIL LIKE '%@%.%');

ALTER TABLE TRACK ADD CONSTRAINT chk_t_duration CHECK (T_DURATION > 0);
