
ALTER TABLE SUBSCRIPTION 
ADD CONSTRAINT chk_s_type CHECK (S_TYPE IN ('Free', 'Premium'));

ALTER TABLE SUBSCRIPTION 
ADD CONSTRAINT chk_s_status CHECK (S_STATUS IN ('Active', 'Expired'));

ALTER TABLE ALBUM 
ADD CONSTRAINT chk_a_popularity CHECK (A_POPULARITY BETWEEN 0 AND 100);

ALTER TABLE TRACK 
ADD CONSTRAINT chk_t_duration CHECK (T_DURATION > 0);

ALTER TABLE TRACK 
ADD CONSTRAINT chk_t_isrc_length CHECK (LENGTH(T_ISRC) >= 12);

ALTER TABLE USER 
ADD CONSTRAINT chk_u_email_format CHECK (U_EMAIL LIKE '%@%.%');

ALTER TABLE USER 
ADD CONSTRAINT chk_u_reg_date CHECK (U_REGISTRATION_DATE <= CURRENT_DATE);

ALTER TABLE GENRE 
ADD CONSTRAINT chk_g_popularity CHECK (G_POPULARITY BETWEEN 0 AND 100);